export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-12 sm:px-6 sm:py-16">
      <h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Terms of Service</h1>
      <p className="mt-1 text-sm text-stone-500">Effective September 16, 2026</p>

      <div className="mt-8 flex flex-col gap-6 text-sm leading-relaxed text-stone-700">
        <p>
          These terms govern your use of VidSage (the "Service"). By signing in and using the
          Service, you agree to them.
        </p>

        <section>
          <h2 className="text-base font-semibold text-stone-900">The Service</h2>
          <p className="mt-2">
            VidSage lets you generate an AI summary of a public YouTube video and ask follow-up
            questions about it. Summaries and answers are generated by AI and may be incomplete
            or inaccurate — don't rely on them for anything where being wrong would matter.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-stone-900">Accounts</h2>
          <p className="mt-2">
            You sign in with Google. You're responsible for keeping your Google account secure —
            anyone with access to it can access your VidSage account and credit balance.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-stone-900">Credits and payments</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>New accounts receive a number of free credits to try the Service.</li>
            <li>Additional credits are purchased one-time — there is no subscription.</li>
            <li>Purchased credits do not expire.</li>
            <li>One credit is spent each time you ask a question that gets answered.</li>
            <li>
              All payments are processed by Stripe. If a purchase fails to deliver credits, or you
              want to request a refund on an unused purchase, email us within 14 days of the
              charge — see Contact below.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-stone-900">Acceptable use</h2>
          <p className="mt-2">You agree not to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Use the Service for anything illegal or to generate harmful content.</li>
            <li>Attempt to circumvent the credit system or abuse free-credit signups.</li>
            <li>Scrape, resell, or redistribute the Service or its output at scale without permission.</li>
            <li>Attempt to disrupt or gain unauthorized access to the Service.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-stone-900">Video content</h2>
          <p className="mt-2">
            VidSage does not host or claim ownership of any YouTube video. Summaries and answers
            are derived from publicly available captions and metadata for the video you point us
            to; the underlying video remains the property of its creator and YouTube.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-stone-900">Termination</h2>
          <p className="mt-2">
            We may suspend or terminate your access to the Service if you violate these terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-stone-900">Disclaimer and limitation of liability</h2>
          <p className="mt-2">
            The Service is provided "as is," without warranties of any kind. To the maximum
            extent permitted by law, VidSage is not liable for any indirect, incidental, or
            consequential damages arising from your use of the Service, and our total liability
            for any claim is limited to the amount you paid us in the past 12 months.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-stone-900">Governing law</h2>
          <p className="mt-2">These terms are governed by the laws of the State of Washington, USA, without regard to
            its conflict of law principles.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-stone-900">Changes to these terms</h2>
          <p className="mt-2">
            We may update these terms from time to time. We'll update the effective date above
            when we do.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-stone-900">Contact</h2>
          <p className="mt-2">
            Questions about these terms?{" "}
            <a href="mailto:kaabeerjr2@gmail.com" className="text-brand-700 hover:underline">
              kaabeerjr2@gmail.com
            </a>
          </p>
        </section>
      </div>
    </main>
  );
}
